import { IDX80_TICKERS } from "./idx80";

/**
 * Broader liquid/active IDX universe.
 *
 * This deliberately goes beyond IDX80 while still avoiding a blind 900+ ticker
 * crawl in the daily job. The scoring pipeline then applies liquidity and
 * reward/risk filters, so non-IDX80 names can enter recommendations when the
 * setup is strong enough.
 */
export const EXPANDED_IDX_TICKERS: string[] = Array.from(
  new Set([
    ...IDX80_TICKERS,
    "AADI",
    "ABMM",
    "ACST",
    "ADCP",
    "ADHI",
    "AISA",
    "AMAR",
    "APIC",
    "APLN",
    "ARCI",
    "AREA",
    "ARKO",
    "ASLC",
    "AUTO",
    "AVIA",
    "AYAM",
    "BABP",
    "BANK",
    "BAPA",
    "BBHI",
    "BBKP",
    "BBYB",
    "BCAP",
    "BDMN",
    "BELI",
    "BIPI",
    "BIRD",
    "BKSW",
    "BLTZ",
    "BMAS",
    "BNGA",
    "BREN",
    "BRIS",
    "BRMS",
    "BUKA",
    "BUMI",
    "BVIC",
    "CASS",
    "CLEO",
    "CMRY",
    "COAL",
    "CUAN",
    "DILD",
    "DMMX",
    "DRMA",
    "DSNG",
    "DSSA",
    "ELPI",
    "ENRG",
    "ESSA",
    "FILM",
    "FIRE",
    "FREN",
    "GEMS",
    "GIAA",
    "GJTL",
    "GOOD",
    "GTSI",
    "HMSP",
    "HOKI",
    "HUMI",
    "ICBP",
    "IMAS",
    "IMJS",
    "INDY",
    "INET",
    "IPCC",
    "IPTV",
    "IRRA",
    "JARR",
    "JATI",
    "KEEN",
    "KIJA",
    "LINK",
    "LPCK",
    "LPKR",
    "LSIP",
    "MARK",
    "MAXI",
    "MCAS",
    "MIDI",
    "MINA",
    "MORA",
    "MSIN",
    "MYOR",
    "NCKL",
    "NISP",
    "PANI",
    "PBRX",
    "PIPA",
    "PNBN",
    "PNLF",
    "POWR",
    "PSAB",
    "PTMP",
    "PURI",
    "SCMA",
    "SGER",
    "SILO",
    "SIMP",
    "SMIL",
    "SOCI",
    "SRAJ",
    "SSIA",
    "TAPG",
    "TBIG",
    "TCPI",
    "TOBA",
    "TOTL",
    "TRIN",
    "ULTJ",
    "WIFI",
    "WOOD",
    "WOWS",
    "ZATA",
  ]),
).sort();

export function parseTickerUniverse(value: string | undefined): string[] {
  if (!value?.trim()) return EXPANDED_IDX_TICKERS;

  const parsed = value
    .split(",")
    .map((ticker) => ticker.trim().toUpperCase())
    .filter(Boolean);

  return Array.from(new Set(parsed));
}
